/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        dark: '#050505',
        card: '#0f0f0f',
        primary: '#ffb3b1',
        secondary: '#c7c6c6',
        'text-primary': '#FFFFFF',
        'text-secondary': '#A0A0A0',
        "surface-container": "#201f1f",
        "on-secondary-fixed": "#1a1c1c",
        "on-tertiary-container": "#00302c",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "on-secondary": "#2f3131",
        "primary-fixed": "#ffdad8",
        "surface-container-low": "#1c1b1b",
        "error": "#ffb4ab",
        "text-muted": "#A0A0A0",
        "on-primary-container": "#5b000e",
        "tertiary-container": "#2fa096",
        "surface-dim": "#131313",
        "on-surface-variant": "#e4bebc",
        "on-primary-fixed": "#410007",
        "on-secondary-container": "#b8b8b8",
        "on-tertiary": "#003733",
        "inverse-primary": "#bb152c",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed": "#00201d",
        "on-primary": "#680011",
        "primary-fixed-dim": "#ffb3b1",
        "outline": "#ab8987",
        "surface-container-highest": "#353534",
        "secondary-container": "#484949",
        "tertiary-fixed-dim": "#6fd8cc",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#464747",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "surface-tint": "#ffb3b1",
        "on-tertiary-fixed-variant": "#00504a",
        "background-deep": "#050505",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#c7c6c6",
        "surface": "#131313",
        "tertiary-fixed": "#8cf4e8",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "surface-glass": "rgba(15, 15, 15, 0.7)",
        "background": "#131313",
        "primary-container": "#ff535b",
        "surface-variant": "#353534",
        "tertiary": "#6fd8cc",
        "accent-glow": "rgba(230, 57, 70, 0.15)",
        "secondary-fixed": "#e3e2e2",
        "surface-bright": "#3a3939",
        "outline-variant": "#5b403f",
        "on-primary-fixed-variant": "#92001c"
      },
      fontFamily: {
        heading: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        "headline-lg": ["Space Grotesk"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1200px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "unit": "8px"
      },
      boxShadow: {
        'glow-red': '0 0 20px rgba(230, 57, 70, 0.3)',
        'glow-red-lg': '0 0 40px rgba(230, 57, 70, 0.4)',
      },
    },
  },
  plugins: [],
}
