/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        dark: 'var(--color-dark)',
        card: 'var(--color-dark-card)',
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        'text-primary': 'var(--color-text)',
        'text-secondary': 'var(--color-text-muted)',
        "surface-container": "var(--color-card)",
        "border-subtle": "var(--color-border)",
        "on-secondary-fixed": "#1a1c1c",
        "on-tertiary-container": "#00302c",
        "on-secondary": "#2f3131",
        "primary-fixed": "#ffdad8",
        "surface-container-low": "var(--color-dark)",
        "error": "#ffb4ab",
        "text-muted": "var(--color-text-muted)",
        "on-primary-container": "var(--color-text-muted)",
        "tertiary-container": "var(--color-card)",
        "surface-dim": "var(--color-dark)",
        "on-surface-variant": "var(--color-text-muted)",
        "on-primary-fixed": "#410007",
        "on-secondary-container": "var(--color-text-muted)",
        "on-tertiary": "#003733",
        "inverse-primary": "var(--color-secondary)",
        "on-background": "var(--color-text)",
        "on-tertiary-fixed": "#00201d",
        "on-primary": "var(--color-text)",
        "primary-fixed-dim": "var(--color-primary)",
        "outline": "var(--color-border)",
        "surface-container-highest": "var(--color-card)",
        "secondary-container": "var(--color-card)",
        "tertiary-fixed-dim": "#6fd8cc",
        "on-surface": "var(--color-text)",
        "on-secondary-fixed-variant": "#464747",
        "surface-container-high": "var(--color-card)",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "surface-tint": "var(--color-primary)",
        "on-tertiary-fixed-variant": "#00504a",
        "background-deep": "var(--color-dark)",
        "error-container": "#93000a",
        "surface-container-lowest": "var(--color-dark-card)",
        "secondary-fixed-dim": "var(--color-secondary)",
        "surface": "var(--color-dark-card)",
        "tertiary-fixed": "#8cf4e8",
        "inverse-surface": "var(--color-text)",
        "inverse-on-surface": "var(--color-dark)",
        "surface-glass": "var(--color-glass-bg)",
        "background": "var(--color-dark)",
        "primary-container": "var(--color-secondary)",
        "surface-variant": "var(--color-card)",
        "tertiary": "var(--color-primary)",
        "accent-glow": "rgba(var(--color-primary-rgb), 0.15)",
        "secondary-fixed": "#e3e2e2",
        "surface-bright": "var(--color-dark)",
        "outline-variant": "var(--color-border)",
        "on-primary-fixed-variant": "#92001c"
      },
      fontFamily: {
        heading: ['var(--font-heading)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        "headline-lg": ['var(--font-heading)'],
        "label-sm": ['var(--font-mono)', 'monospace'],
        "body-lg": ['var(--font-body)'],
        "headline-lg-mobile": ['var(--font-heading)'],
        "headline-xl": ['var(--font-heading)'],
        "headline-md": ['var(--font-heading)'],
        "body-md": ['var(--font-body)']
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1200px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "unit": "8px"
      },
      boxShadow: {
        'glow-red': '0 0 20px rgba(var(--color-primary-rgb), 0.3)',
        'glow-red-lg': '0 0 40px rgba(var(--color-primary-rgb), 0.4)',
      },
    },
  },
  plugins: [],
}
